version: "3"
services:
  postgres:
    image: postgres
    container_name: "my_postgres"
    env_file:
      - .env
    ports:
      - "10.1.1.245:54320:5432"
    networks:
      - postgres
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}


volumes:
  my_dbdata:

networks:
  postgres:
    driver: bridge
